//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Form17Entities : DbContext
    {
        public Form17Entities()
            : base("name=Form17Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Center> Tbl_Center { get; set; }
        public virtual DbSet<Tbl_Center_Details> Tbl_Center_Details { get; set; }
        public virtual DbSet<Tbl_Code_Master> Tbl_Code_Master { get; set; }
        public virtual DbSet<Tbl_Colmst> Tbl_Colmst { get; set; }
        public virtual DbSet<Tbl_HSC_Form17> Tbl_HSC_Form17 { get; set; }
        public virtual DbSet<Tbl_HSC_Form17_Final> Tbl_HSC_Form17_Final { get; set; }
        public virtual DbSet<Tbl_HSC_Payment> Tbl_HSC_Payment { get; set; }
        public virtual DbSet<Tbl_HSC_Payment_Error> Tbl_HSC_Payment_Error { get; set; }
        public virtual DbSet<Tbl_Login_Credentials> Tbl_Login_Credentials { get; set; }
        public virtual DbSet<Tbl_Site_Status> Tbl_Site_Status { get; set; }
        public virtual DbSet<Tbl_SSC_Form17> Tbl_SSC_Form17 { get; set; }
        public virtual DbSet<Tbl_SSC_Form17_Final> Tbl_SSC_Form17_Final { get; set; }
        public virtual DbSet<Tbl_SSC_Payment> Tbl_SSC_Payment { get; set; }
        public virtual DbSet<Tbl_SSC_Payment_Error> Tbl_SSC_Payment_Error { get; set; }
        public virtual DbSet<Tbl_Unique_ID_Payment> Tbl_Unique_ID_Payment { get; set; }
        public virtual DbSet<Tbl_Update_Old_College> Tbl_Update_Old_College { get; set; }
        public virtual DbSet<Tbl_OTP> Tbl_OTP { get; set; }
        public virtual DbSet<Tbl_Division_Details> Tbl_Division_Details { get; set; }
    
        public virtual int INSERT_DATA_HSC(string s_id, string div, ObjectParameter rESULT)
        {
            var s_idParameter = s_id != null ?
                new ObjectParameter("s_id", s_id) :
                new ObjectParameter("s_id", typeof(string));
    
            var divParameter = div != null ?
                new ObjectParameter("div", div) :
                new ObjectParameter("div", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_DATA_HSC", s_idParameter, divParameter, rESULT);
        }
    
        public virtual int INSERT_DATA_SSC(string s_id, string div, ObjectParameter rESULT)
        {
            var s_idParameter = s_id != null ?
                new ObjectParameter("s_id", s_id) :
                new ObjectParameter("s_id", typeof(string));
    
            var divParameter = div != null ?
                new ObjectParameter("div", div) :
                new ObjectParameter("div", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_DATA_SSC", s_idParameter, divParameter, rESULT);
        }
    }
}
