//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Tbl_SSC_Form17_Final
    {
        public int ID { get; set; }
        public string S_ID { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Father_Husband_Name { get; set; }
        public string Mother_Name { get; set; }
        public string Gender { get; set; }
        public string Residential_Address { get; set; }
        public string Pincode { get; set; }
        public string District { get; set; }
        public string Taluka { get; set; }
        public string State { get; set; }
        public string Aadhar_No { get; set; }
        public string Mobile_No { get; set; }
        public string Email_ID { get; set; }
        public string DOB { get; set; }
        public string Village_of_Birth { get; set; }
        public string Taluka_of_Birth { get; set; }
        public string District_of_Birth { get; set; }
        public string Name_of_Secondary_School { get; set; }
        public string Secondary_School_Village { get; set; }
        public string Secondary_School_Taluka { get; set; }
        public string Secondary_School_District { get; set; }
        public string Secondary_School_State { get; set; }
        public string Secondary_School_Udise_No { get; set; }
        public string Secondary_School_Pincode { get; set; }
        public string Whether_Handicap { get; set; }
        public string Handicap_Category { get; set; }
        public string Date_of_Leaving_Secondary_School { get; set; }
        public string Last_Studied_Standard { get; set; }
        public string Status_of_Last_Studied_Standard { get; set; }
        public string Division { get; set; }
        public string District_of_Form_Submission { get; set; }
        public string Taluka_of_Form_Submission { get; set; }
        public string Medium_of_Form { get; set; }
        public string School_of_Form_Submission { get; set; }
        public string Index_No_of_School { get; set; }
        public string Declaration_Yes_No { get; set; }
        public string Name_of_Debarred_Board { get; set; }
        public string Exam_of_Debar { get; set; }
        public string Debarred_From_Year { get; set; }
        public string Debarred_To_Year { get; set; }
        public string Leaving_Certificate_Yes_No { get; set; }
        public string Duplicate_Leaving_Certificate_Yes_No { get; set; }
        public string Unique_ID_Payment { get; set; }
        public string Selected_Language { get; set; }
        public string EC_Status { get; set; }
        public string EC_Code { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string EC_Date { get; set; }
    
        public virtual Tbl_SSC_Form17 Tbl_SSC_Form17 { get; set; }
        public HttpPostedFileBase SSC_Photo { get; set; }
        public HttpPostedFileBase SSC_LC { get; set; }
        public HttpPostedFileBase SSC_Domicile { get; set; }
        public HttpPostedFileBase SSC_Handicap_Certificate { get; set; }
    }
}
