//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HSC_Payment_Error
    {
        public int ID { get; set; }
        public string pgRespCode { get; set; }
        public string PGTxnNo { get; set; }
        public string SabPaisaTxId { get; set; }
        public string issuerRefNo { get; set; }
        public string authIdCode { get; set; }
        public string amount { get; set; }
        public string clientTxnId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string payMode { get; set; }
        public string email { get; set; }
        public string mobileNo { get; set; }
        public string spRespCode { get; set; }
        public string cid { get; set; }
        public string bid { get; set; }
        public string clientCode { get; set; }
        public string payeeProfile { get; set; }
        public string transDate { get; set; }
        public string spRespStatus { get; set; }
        public string m3 { get; set; }
        public string challanNo { get; set; }
        public string reMsg { get; set; }
        public string orgTxnAmount { get; set; }
        public string programId { get; set; }
        public string midName { get; set; }
        public string Add { get; set; }
        public string param1 { get; set; }
        public string param2 { get; set; }
        public string param3 { get; set; }
        public string param4 { get; set; }
        public string udf5 { get; set; }
        public string udf6 { get; set; }
        public string udf7 { get; set; }
        public string udf8 { get; set; }
        public string udf9 { get; set; }
        public string udf10 { get; set; }
        public string udf11 { get; set; }
        public string udf12 { get; set; }
        public string udf13 { get; set; }
        public string udf14 { get; set; }
        public string udf15 { get; set; }
        public string udf16 { get; set; }
        public string udf17 { get; set; }
        public string udf18 { get; set; }
        public string udf19 { get; set; }
        public string udf20 { get; set; }
    }
}
