//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Center_Details
    {
        public int ID { get; set; }
        public string Index_No { get; set; }
        public Nullable<int> STD { get; set; }
        public string Stream { get; set; }
        public string Medium { get; set; }
    }
}
