//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Colmst
    {
        public int ID { get; set; }
        public string SCHNO { get; set; }
        public string NAME { get; set; }
        public string DIV_C_1 { get; set; }
        public string STREAM { get; set; }
        public string MEDIUM { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<double> Active { get; set; }
    }
}
