//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Division_Details
    {
        public int ID { get; set; }
        public string Division_Code { get; set; }
        public string Division_Name { get; set; }
        public string Mobile_No { get; set; }
    }
}
