//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Tbl_HSC_Form17_Final
    {
        public int ID { get; set; }
        public string S_ID { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Father_Husband_Name { get; set; }
        public string Mother_Name { get; set; }
        public string Gender { get; set; }
        public string Residential_Address { get; set; }
        public string Pincode { get; set; }
        public string District { get; set; }
        public string Taluka { get; set; }
        public string State { get; set; }
        public string Aadhar_No { get; set; }
        public string Mobile_No { get; set; }
        public string Email_ID { get; set; }
        public string DOB { get; set; }
        public string Village_of_Birth { get; set; }
        public string Taluka_of_Birth { get; set; }
        public string District_of_Birth { get; set; }
        public string SSC_Passing_Month { get; set; }
        public string SSC_Passing_Year { get; set; }
        public string SSC_Division_Board { get; set; }
        public string Other_SSC_Board { get; set; }
        public string Date_of_Leaving_Secondary_School { get; set; }
        public string Date_of_Leaving_Junior_College { get; set; }
        public string Name_of_Secondary_School { get; set; }
        public string Secondary_School_Village { get; set; }
        public string Secondary_School_Taluka { get; set; }
        public string Secondary_School_District { get; set; }
        public string Secondary_School_State { get; set; }
        public string Secondary_School_Index_No { get; set; }
        public string Secondary_School_Udise_No { get; set; }
        public string Attended_Junior_College_Yes_No { get; set; }
        public string Name_of_Junior_College { get; set; }
        public string Junior_College_Village { get; set; }
        public string Junior_College_District { get; set; }
        public string Junior_College_State { get; set; }
        public string Junior_College_Index_No { get; set; }
        public string Junior_College_Udise_No { get; set; }
        public string Junior_College_Stream { get; set; }
        public string FYJC_Passing_Month { get; set; }
        public string FYJC_Passing_Year { get; set; }
        public string FYJC_Passing_Status { get; set; }
        public string Division { get; set; }
        public string District_of_Form_Submission { get; set; }
        public string Taluka_of_Form_Submission { get; set; }
        public string Stream_of_Form { get; set; }
        public string Medium_of_Form { get; set; }
        public string College_of_Form_Submission { get; set; }
        public string College_Index_No { get; set; }
        public string Declaration_Yes_No { get; set; }
        public string Name_of_Debarred_Board { get; set; }
        public string Exam_of_Debar { get; set; }
        public string Debarred_From_Year { get; set; }
        public string Debarred_To_Year { get; set; }
        public string Secondary_School_Certificate_Yes_No { get; set; }
        public string FYJC_Leaving_Certificate_Yes_No { get; set; }
        public string School_Leaving_Certificate_Yes_No { get; set; }
        public string School_Leaving_Duplicate_Certificate_Yes_No { get; set; }
        public string Unique_ID_Payment { get; set; }
        public string Selected_Language { get; set; }
        public string EC_Status { get; set; }
        public string EC_Code { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string EC_Date { get; set; }
    
        public virtual Tbl_HSC_Form17 Tbl_HSC_Form17 { get; set; }
        public HttpPostedFileBase HSC_Photo { get; set; }
        public HttpPostedFileBase HSC_School_LC { get; set; }
        public HttpPostedFileBase HSC_School_Marksheet { get; set; }
        public HttpPostedFileBase HSC_Domicile { get; set; }
        public HttpPostedFileBase JCLC { get; set; }
    }
}
