//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Center
    {
        public int ID { get; set; }
        public string Index_No { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Pin { get; set; }
        public string Div_Code { get; set; }
        public string Division_Name { get; set; }
        public Nullable<int> STD { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
