//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Code_Master
    {
        public int id { get; set; }
        public string division_code { get; set; }
        public string division_name { get; set; }
        public string district_code { get; set; }
        public string district_name { get; set; }
        public string taluka_code { get; set; }
        public string taluka_name { get; set; }
    }
}
