//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Update_Old_College
    {
        public int ID { get; set; }
        public string Form_No { get; set; }
        public string Old_College { get; set; }
        public string Updated_College { get; set; }
        public string Email_ID { get; set; }
    }
}
