//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form17.Models
{
    using System;
    using System.Collections.Generic;

    public partial class UpdateCollegeByDivisionModel
    {
        public int ID { get; set; }
        public string Application_No { get; set; }
        public string S_ID { get; set; }
        public Nullable<int> Ref_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Father_Husband_Name { get; set; }       
        public string District_of_Form_Submission { get; set; }
        public string Taluka_of_Form_Submission { get; set; }
        public string Stream_of_Form { get; set; }
        public string Medium_of_Form { get; set; }
        public string College_of_Form_Submission { get; set; }
        public string College_Index_No { get; set; }
        

        public virtual Tbl_HSC_Form17 Tbl_HSC_Form17 { get; set; }
    }
}
